if [ -f /etc/bash.bashrc ]; then
  . /etc/bash.bashrc
fi


source ~/.bash/aliases
source ~/.bash/completion_scripts/git_completion

export EDITOR="vim"
# Make less show 2 lines of context each time you page down
# (-z) and do all the smart things you want less to do,
# especially in git (-FRSX)
export LESS='-FRSX -z-4'

if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

if [ -f ~/.localrc ]; then
  . ~/.localrc
fi
