# Solarized color scheme
# Used the following until 4/24/2013.  Then I got the dark and light
# versions, and can now source either to change the background color.  If they
# look OK, I can delete old.solar.dark.
# source ~/.solarized/old.solar.dark
source ~/.solarized/sol.dark

# Make bash append rather than overwrite the history on disk
shopt -s histappend

# When changing directory small typos can be ignored by bash
# for example, cd /vr/lgo/apaache would find /var/log/apache
shopt -s cdspell

# Completion options
# ##################

# These completion tuning parameters change the default behavior of bash_completion:

# If this shell is interactive, turn on programmable completion enhancements.
# Any completions you add in ~/.bash_completion are sourced last.
# case $- in
#   *i*) [[ -f /etc/bash_completion ]] && . /etc/bash_completion ;;
# esac


# History Options
# ###############
export HISTSIZE=1000000
export HISTFILESIZE=1000000

# Don't put duplicate lines in the history.
export HISTCONTROL="ignoredups"

# Ignore some controlling instructions
# export HISTIGNORE="[   ]*:&:bg:fg:exit"

# Whenever displaying the prompt, write the previous line to disk
export PROMPT_COMMAND="history -a"


# Aliases
# #######

# alias grep='grep --color'                     # show differences in colour

alias ls='ls -hF --color=tty'                 # classify files in colour
alias h=history
alias vi=vim
alias rm='rm -i'

function svndiff()
{
  svn diff "$@" | colordiff | less -R && svn diff "$@"
}

export SVN_EDITOR=vim

# Make less show 2 lines of context each time you page down
# (-z) and do all the smart things you want less to do,
# especially in git (-FRSX)
export LESS='-FRSX -z-4'
